id: P15478B02
initial_creation_type: input
source_metadata:
  title: Pema Kunzang Rangdrol
  language: en
  description: 'Texts by and about Muksang Tulku Pema Kunzang Rangdrol (Padma kun
    bzang rang grol, 1916–1984) of the Palyul tradition:'
  volume:
    5d39ca2bedba40ed9287e6ffac8e4dcd:
      title: Brief Biography of Kharlek Tulku Pema Kunzang Rangdrol
      parent: Biography
    5c2b01c3576746e698dbb999ef386ad1:
      title: Annotation Commentary on the Special Teaching of the Wise and Glorious
        King
      parent: Dzogchen
created_at: '2022-03-01T01:16:02.153436'
last_modified_at: '2022-03-01T01:16:02.153442'
